language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh && make && make test

cache:
  directories:
  - $HOME/.opam

env:
  # - OCAML_VERSION=4.00
  # - OCAML_VERSION=4.01
  - OCAML_VERSION=4.02

os:
  - linux
  - osx
