language: c
sudo: required
before_install:
    - curl -L https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh | sh
    - eval $(opam config env)
install:
    make
script:
    make test

cache:
  directories:
  - $HOME/.opam
  - /usr/local

env:
  - OCAML_VERSION=4.10

os:
  - linux
  - osx

# BCP and brabalan, 1/19: We took away the OSX build because it is
# horribly slow and 98% redundant...
