blank_issues_enabled: false
contact_links:
  - name: Asking for Help
    url: https://github.com/bcpierce00/unison/wiki/Mailing-Lists
    about: Please direct questions the unison-users@ list, or unison-hackers@ if reading source code is helpful.
  - name: Feature Requests (not fully worked out)
    url: https://github.com/bcpierce00/unison/wiki/Mailing-Lists
    about: Please bring up feature requests that are not fully designed on a mailing list.
